import requests
import json

def make_request(masterKey: str, address: str, actions: list, indexes: list, 
                 description: str = 'Key generated by meilisearch_api_key_gen', expiresAt: str = None):
    payload = {
        'description': description,
        'actions': actions, # ['*'] for all,
        'indexes': indexes, # ['*'] for all,
        'expiresAt': expiresAt,
    }
    r = requests.post(f'{address}/keys',  
        headers={'Content-Type': 'application/json', 'Authorization': f'Bearer {masterKey}'}, 
        data=json.dumps(payload),
    )
    return r